import { DragEvent, FormEvent, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Bot, Box, Boxes, CalendarDays, Check, ChevronDown, ChevronRight, CircleDollarSign, CirclePlus, Clock3, Download, Filter, GripVertical, IndianRupee, Mail, MessageSquare, MoreHorizontal, Package, PackageCheck, Paperclip, Pencil, Phone, Plus, RotateCcw, Search, Send, ShoppingBag, Sparkles, TrendingUp, UserPlus, Users, WandSparkles, Warehouse, X, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { AdminShell } from '../components/AdminShell';
import { Glass, StatusBadge } from '../components/ui';
import { formatPrice, leads as initialLeads, Product, products } from '../data/catalog';

const revenueData=[{day:'Mon',revenue:128000,orders:58},{day:'Tue',revenue:176000,orders:72},{day:'Wed',revenue:149000,orders:64},{day:'Thu',revenue:224000,orders:91},{day:'Fri',revenue:203000,orders:83},{day:'Sat',revenue:287000,orders:112},{day:'Sun',revenue:264000,orders:104}];
const sourceData=[{name:'Online store',value:62,color:'#7c3aed'},{name:'Direct sales',value:24,color:'#f97316'},{name:'Marketplace',value:14,color:'#c4b5fd'}];
const adminOrders=[
  {id:'DOS-847291',customer:'Ananya Kapoor',initials:'AK',channel:'Online',value:14672,status:'Processing',time:'2 min ago'},
  {id:'DOS-847290',customer:'Rahul Bedi',initials:'RB',channel:'Direct',value:48990,status:'Paid',time:'18 min ago'},
  {id:'DOS-847289',customer:'Maya Iyer',initials:'MI',channel:'Online',value:8499,status:'Shipped',time:'32 min ago'},
  {id:'DOS-847288',customer:'Dev Patel',initials:'DP',channel:'Marketplace',value:24999,status:'Paid',time:'1 hr ago'},
];

export function AdminDashboardPage(){
  return <AdminShell title="Good morning, Ananya." subtitle="Here’s what’s happening across DOS Commerce today." action={<div className="admin-title-actions"><button className="admin-date"><CalendarDays/> 21–27 Aug <ChevronDown/></button><button className="btn btn-primary btn-sm"><Download/> Export report</button></div>}>
    <div className="kpi-bento">
      <KpiCard icon={IndianRupee} label="Net revenue" value="₹14.8L" change="+18.4%" positive tone="purple" chart={[28,37,34,46,44,62,67]}/>
      <KpiCard icon={ShoppingBag} label="Orders" value="1,284" change="+12.1%" positive tone="orange" chart={[40,32,48,42,55,59,72]}/>
      <KpiCard icon={Boxes} label="Stock value" value="₹82.6L" change="+4.2%" positive tone="blue" chart={[49,51,50,54,57,60,63]}/>
      <KpiCard icon={PackageCheck} label="Low stock" value="14" change="Needs action" tone="red" chart={[72,61,58,43,48,35,31]}/>
      <Glass className="pipeline-kpi"><div><span className="kpi-icon green"><TrendingUp/></span><span><small>Active pipeline</small><strong>₹36.4L</strong></span></div><div className="pipeline-bars">{['New','Qualified','Proposal','Won'].map((x,i)=><span key={x}><i style={{height:`${[35,58,78,46][i]}%`}}/><small>{x}</small></span>)}</div><p><b>24 deals</b> across 4 stages <span>+8.7%</span></p></Glass>
      <Glass className="goal-kpi"><div className="goal-ring"><svg viewBox="0 0 42 42"><circle cx="21" cy="21" r="16"/><circle className="progress" cx="21" cy="21" r="16"/></svg><span><b>74%</b><small>of goal</small></span></div><div><small>Monthly target</small><strong>₹14.8L <i>/ ₹20L</i></strong><p>₹5.2L to go · 4 days left</p></div></Glass>
    </div>
    <div className="dashboard-grid">
      <Glass className="revenue-panel"><PanelHead eyebrow="Performance" title="Revenue overview" action={<div className="chart-legend"><span><i/>Revenue</span><button>7 days <ChevronDown/></button></div>}/><div className="revenue-summary"><strong>₹14,82,640</strong><span><ArrowUpRight/> 18.4%</span><small>vs ₹12,52,180 last week</small></div><div className="revenue-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenueData}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7c3aed" stopOpacity=".32"/><stop offset="1" stopColor="#7c3aed" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(80,60,100,.07)"/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fontSize:8,fill:'#8b8791'}}/><YAxis tickLine={false} axisLine={false} tick={{fontSize:8,fill:'#8b8791'}} tickFormatter={v=>`${v/1000}k`}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid rgba(100,80,120,.1)',fontSize:9}} formatter={(v)=>formatPrice(Number(v))}/><Area type="monotone" dataKey="revenue" stroke="#7c3aed" strokeWidth={2.5} fill="url(#revenueFill)"/></AreaChart></ResponsiveContainer></div></Glass>
      <Glass className="channel-panel"><PanelHead eyebrow="Channels" title="Order sources" action={<button className="dot-action"><MoreHorizontal/></button>}/><div className="source-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={sourceData} dataKey="value" innerRadius={60} outerRadius={82} paddingAngle={4}>{sourceData.map(s=><Cell fill={s.color} key={s.name}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div><b>1,284</b><small>Total orders</small></div></div><div className="source-legend">{sourceData.map(s=><span key={s.name}><i style={{background:s.color}}/><b>{s.name}</b><strong>{s.value}%</strong></span>)}</div></Glass>
      <Glass className="recent-orders-panel"><PanelHead eyebrow="Live orders" title="Recent orders" action={<Link to="/admin">View all <ArrowRight/></Link>}/><div className="admin-table orders-table"><div className="table-head"><span>Order</span><span>Customer</span><span>Channel</span><span>Amount</span><span>Status</span><span/></div>{adminOrders.map((o,i)=><div className="table-row" key={o.id}><span><b>#{o.id}</b><small>{o.time}</small></span><span className="table-customer"><i>{o.initials}</i><b>{o.customer}</b></span><span>{o.channel}</span><strong>{formatPrice(o.value)}</strong><StatusBadge tone={i===0?'orange':i===2?'purple':'green'}>{o.status}</StatusBadge><button><ChevronRight/></button></div>)}</div></Glass>
      <Glass className="quick-actions"><PanelHead eyebrow="Do it faster" title="Quick actions"/><div>{[{icon:CirclePlus,label:'New order',tone:'purple'},{icon:UserPlus,label:'Add lead',tone:'orange'},{icon:Package,label:'Add product',tone:'blue'},{icon:WandSparkles,label:'Ask DOS AI',tone:'green'}].map(a=><button key={a.label} onClick={()=>a.label==='Ask DOS AI'&&(window.location.href='/admin/ai')}><span className={a.tone}><a.icon/></span><b>{a.label}</b><ChevronRight/></button>)}</div></Glass>
      <Glass className="low-stock-panel"><PanelHead eyebrow="Inventory alert" title="Running low" action={<Link to="/admin/inventory">View inventory</Link>}/>{products.filter(p=>p.stock<20).slice(0,3).map(p=><div className="low-stock-row" key={p.id}><img src={p.image}/><span><b>{p.name}</b><small>{p.sku}</small></span><strong className={p.stock<10?'danger':''}>{p.stock} left</strong><i><span style={{width:`${p.stock*4}%`}}/></i></div>)}</Glass>
    </div>
  </AdminShell>
}

function KpiCard({icon:Icon,label,value,change,positive=false,tone,chart}:{icon:typeof Activity;label:string;value:string;change:string;positive?:boolean;tone:string;chart:number[]}){
  const data=chart.map((v,i)=>({i,v}));
  return <Glass className="kpi-card"><div className="kpi-top"><span className={`kpi-icon ${tone}`}><Icon/></span><span className={`kpi-change ${positive?'positive':''}`}>{positive?<ArrowUpRight/>:<Clock3/>}{change}</span></div><small>{label}</small><strong>{value}</strong><div className="kpi-spark"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><Area type="monotone" dataKey="v" stroke={tone==='orange'?'#f97316':tone==='red'?'#ef4444':'#7c3aed'} strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div></Glass>
}
function PanelHead({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}){return <div className="panel-head"><div><span>{eyebrow}</span><h2>{title}</h2></div>{action}</div>}

export function InventoryPage(){
  const [items,setItems]=useState(products);const [query,setQuery]=useState('');const [category,setCategory]=useState('All');const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Product|null>(null);
  const visible=items.filter(p=>(category==='All'||p.category===category)&&(p.name.toLowerCase().includes(query.toLowerCase())||p.sku.toLowerCase().includes(query.toLowerCase())));
  const openAdd=()=>{setEditing(null);setModal(true)};const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(editing){setItems(cur=>cur.map(p=>p.id===editing.id?{...p,name:(new FormData(e.currentTarget).get('name') as string)||p.name}:p))}else{setItems(cur=>[...cur,{...products[0],id:`new-${Date.now()}`,name:(new FormData(e.currentTarget).get('name') as string)||'New product',sku:'DOS-NEW-001',stock:25}])}setModal(false)};
  return <AdminShell title="Inventory" subtitle="Manage products, stock levels, and catalog availability." action={<div className="admin-title-actions"><button className="btn btn-ghost btn-sm"><Download/> Export</button><button className="btn btn-primary btn-sm" onClick={openAdd}><Plus/> Add product</button></div>}>
    <div className="inventory-kpis"><InventoryKpi icon={Package} label="Total products" value={String(items.length)} meta="6 categories" tone="purple"/><InventoryKpi icon={Warehouse} label="Stock value" value="₹82.6L" meta="Across 3 locations" tone="blue"/><InventoryKpi icon={PackageCheck} label="Low stock" value="14" meta="4 critical" tone="orange"/><InventoryKpi icon={RotateCcw} label="Stock turnover" value="4.8×" meta="+0.6 this month" tone="green"/></div>
    <Glass className="inventory-panel"><div className="inventory-toolbar"><div className="inventory-search"><Search/><input placeholder="Search name, SKU, or category…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="category-tabs">{['All','Electronics','Industrial','Office'].map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><button className="filter-button"><Filter/> Filter <i>2</i></button></div>
      <div className="admin-table inventory-table"><div className="table-head"><span>Product</span><span>SKU</span><span>Category</span><span>Stock</span><span>Price</span><span>Status</span><span/></div>{visible.map(p=><div className="table-row clickable" key={p.id} onClick={()=>{setEditing(p);setModal(true)}}><span className="product-table-cell"><img src={p.image}/><span><b>{p.name}</b><small>{p.brand}</small></span></span><code>{p.sku}</code><span>{p.category}</span><span className="stock-cell"><b>{p.stock}</b><i><em style={{width:`${Math.min(p.stock,100)}%`}}/></i></span><strong>{formatPrice(p.price)}</strong><StatusBadge tone={p.stock<10?'red':p.stock<20?'orange':'green'}>{p.stock<10?'Critical':p.stock<20?'Low stock':'In stock'}</StatusBadge><button><MoreHorizontal/></button></div>)}</div><div className="table-footer"><span>Showing 1–{visible.length} of {visible.length} products</span><div><button>‹</button><button className="active">1</button><button>2</button><button>3</button><button>›</button></div></div>
    </Glass>{modal&&<ProductModal product={editing} onClose={()=>setModal(false)} onSave={save}/>} 
  </AdminShell>
}
function InventoryKpi({icon:Icon,label,value,meta,tone}:{icon:typeof Package;label:string;value:string;meta:string;tone:string}){return <Glass className="inventory-kpi"><span className={`kpi-icon ${tone}`}><Icon/></span><div><small>{label}</small><strong>{value}</strong><p>{meta}</p></div></Glass>}
function ProductModal({product,onClose,onSave}:{product:Product|null;onClose:()=>void;onSave:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><Glass className="product-modal"><div className="modal-head"><div><span className="eyebrow">Catalog manager</span><h2>{product?'Edit product':'Add a new product'}</h2></div><button onClick={onClose}><X/></button></div><form onSubmit={onSave}><div className="modal-image"><div>{product?<img src={product.image}/>:<Package/>}</div><button type="button">Upload image</button><small>PNG or JPG up to 5 MB</small></div><div className="modal-fields"><label>Product name<input name="name" defaultValue={product?.name} placeholder="e.g. Aura Pro Headphones" required/></label><div className="field-row"><label>SKU<input defaultValue={product?.sku}/></label><label>Category<select defaultValue={product?.category}><option>Electronics</option><option>Industrial</option><option>Office</option><option>Packaging</option></select></label></div><div className="field-row"><label>Selling price<input type="number" defaultValue={product?.price}/></label><label>Opening stock<input type="number" defaultValue={product?.stock}/></label></div><label>Description<textarea defaultValue={product?.description}/></label></div><div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={onClose}>Cancel</button><button className="btn btn-primary" type="submit">{product?'Save changes':'Add product'} <ArrowRight/></button></div></form></Glass></div>}

const stages=['New','Contacted','Qualified','Proposal','Won'];
export function CRMLeadsPage(){
  const [leads,setLeads]=useState(initialLeads);const [selected,setSelected]=useState<typeof initialLeads[0]|null>(null);const [dragging,setDragging]=useState<number|null>(null);const [search,setSearch]=useState('');
  const drop=(stage:string)=>{if(dragging===null)return;setLeads(cur=>cur.map(l=>l.id===dragging?{...l,stage}:l));setDragging(null)};
  const visible=leads.filter(l=>`${l.name} ${l.company}`.toLowerCase().includes(search.toLowerCase()));
  return <AdminShell title="CRM pipeline" subtitle="Move opportunities forward and close with confidence." action={<button className="btn btn-primary btn-sm"><Plus/> Add lead</button>}>
    <div className="crm-toolbar"><Glass className="crm-search"><Search/><input placeholder="Search leads or companies…" value={search} onChange={e=>setSearch(e.target.value)}/></Glass><div className="crm-summary"><span><i/> Pipeline value <b>{formatPrice(leads.reduce((s,l)=>s+l.value,0))}</b></span><span><Users/> {leads.length} active leads</span><button><Filter/> Filters</button></div></div>
    <div className="kanban-board">{stages.map((stage,index)=>{const stageLeads=visible.filter(l=>l.stage===stage);return <div className="kanban-column" onDragOver={e=>e.preventDefault()} onDrop={()=>drop(stage)} key={stage}><div className="kanban-head"><span className={`stage-dot stage-${index}`}/><b>{stage}</b><em>{stageLeads.length}</em><strong>{formatPrice(stageLeads.reduce((s,l)=>s+l.value,0))}</strong><button><Plus/></button></div><div className="kanban-cards">{stageLeads.map(lead=><article className={`glass lead-card ${dragging===lead.id?'dragging':''}`} draggable onDragStart={()=>setDragging(lead.id)} onClick={()=>setSelected(lead)} key={lead.id}><div className="lead-card-top"><span>{lead.avatar}</span><button><MoreHorizontal/></button></div><h3>{lead.name}</h3><p>{lead.company}</p><div className="lead-value"><CircleDollarSign/><b>{formatPrice(lead.value)}</b></div><div className="lead-bottom"><span><Clock3/> {lead.time}</span><GripVertical/></div></article>)}<button className="add-lead-inline"><Plus/> Add lead</button></div></div>})}</div>
    {selected&&<><div className="drawer-scrim" onClick={()=>setSelected(null)}/><Glass className="lead-drawer"><div className="drawer-head"><button onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">Lead details</span><button><MoreHorizontal/></button></div><div className="lead-profile"><span>{selected.avatar}</span><h2>{selected.name}</h2><p>{selected.company}</p><StatusBadge tone="purple">{selected.stage}</StatusBadge></div><div className="drawer-actions"><button><Phone/> Call</button><button><Mail/> Email</button><button><MessageSquare/> Note</button></div><div className="lead-detail-grid"><div><small>Deal value</small><b>{formatPrice(selected.value)}</b></div><div><small>Probability</small><b>72%</b></div><div><small>Expected close</small><b>12 Sep 2026</b></div><div><small>Owner</small><b>Ananya Kapoor</b></div></div><div className="lead-activity"><h3>Recent activity</h3><div><span><Mail/></span><p><b>Proposal sent</b><small>Yesterday at 4:32 PM</small></p></div><div><span className="orange"><Phone/></span><p><b>Discovery call completed</b><small>24 Aug at 11:20 AM</small></p></div><div><span className="green"><UserPlus/></span><p><b>Lead assigned to you</b><small>21 Aug at 9:05 AM</small></p></div></div><button className="btn btn-primary btn-block">Convert to opportunity <ArrowRight/></button></Glass></>}
  </AdminShell>
}

const initialMessages=[{role:'ai',text:'Good morning, Ananya. I’ve analyzed today’s business data. Revenue is up 18.4% this week, but 14 products need a stock decision. What would you like to explore?',time:'9:41 AM'},{role:'user',text:'Which low-stock products are most likely to sell out this week?',time:'9:42 AM'},{role:'ai',text:'Three products are at high risk based on current sales velocity: Form Ergonomic Chair (9 left, ~2.4 days), Forge X Drill (12 left, ~3.1 days), and Arc 75 Mechanical (18 left, ~4.8 days). I’d prioritize a purchase order for Forma and Forge today.',time:'9:42 AM'}];
export function AIAssistantPage(){
  const [messages,setMessages]=useState(initialMessages);const [input,setInput]=useState('');const [thinking,setThinking]=useState(false);const [conversation,setConversation]=useState(0);
  const send=(text=input)=>{if(!text.trim())return;setMessages(m=>[...m,{role:'user',text,time:'Now'}]);setInput('');setThinking(true);setTimeout(()=>{setMessages(m=>[...m,{role:'ai',text:'Based on the current workspace data, I recommend acting on the highest-impact items first. I can prepare a detailed breakdown, create a draft purchase order, or export this analysis for your team.',time:'Now'}]);setThinking(false)},700)};
  return <AdminShell title="DOS Intelligence" subtitle="Ask questions, analyze your business, and take action." action={<span className="ai-online"><i/> All systems connected</span>}>
    <div className="ai-workspace">
      <Glass className="ai-conversations"><button className="btn btn-primary btn-block"><Plus/> New conversation</button><div className="conversation-search"><Search/><input placeholder="Search conversations"/></div><div className="conversation-group"><span>Today</span>{['Inventory risk analysis','Weekly revenue summary','Top customer segments'].map((c,i)=><button className={conversation===i?'active':''} onClick={()=>setConversation(i)} key={c}><MessageSquare/><span><b>{c}</b><small>{i===0?'2 min ago':i===1?'1 hour ago':'3 hours ago'}</small></span><MoreHorizontal/></button>)}</div><div className="conversation-group"><span>Previous 7 days</span>{['Supplier performance','Q3 sales forecast','GST filing checklist'].map(c=><button key={c}><MessageSquare/><span><b>{c}</b><small>Aug 2026</small></span></button>)}</div><div className="ai-plan"><Sparkles/><div><b>DOS AI Pro</b><small>2,840 credits left</small></div><i><span style={{width:'68%'}}/></i></div></Glass>
      <Glass className="ai-chat"><div className="chat-head"><div><span className="ai-agent-avatar"><Bot/></span><div><b>Business Analyst</b><small><i/> Connected to live data</small></div></div><button><MoreHorizontal/></button></div><div className="chat-messages"><div className="chat-day"><span>Today · 27 August</span></div>{messages.map((m,i)=><div className={`chat-message ${m.role}`} key={i}>{m.role==='ai'&&<span className="ai-agent-avatar"><Bot/></span>}<div><p>{m.text}</p><small>{m.time}{m.role==='ai'&&' · DOS Analyst'}</small>{m.role==='ai'&&i===messages.length-1&&i>1&&<div className="message-actions"><button>View analysis</button><button>Create task</button></div>}</div></div>)}{thinking&&<div className="chat-message ai"><span className="ai-agent-avatar"><Bot/></span><div className="typing"><i/><i/><i/></div></div>}</div><div className="suggestion-chips">{['Show today’s sales','What needs attention?','Forecast next month'].map(s=><button onClick={()=>send(s)} key={s}><Sparkles/> {s}</button>)}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();send()}}><button type="button"><Paperclip/></button><textarea placeholder="Ask anything about your business…" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button className="send-button" type="submit"><Send/></button><span>Press Enter to send · Shift + Enter for new line</span></form></Glass>
      <Glass className="ai-context"><div className="context-head"><span>Live context</span><button><RotateCcw/></button></div><div className="context-health"><div className="health-ring"><svg viewBox="0 0 42 42"><circle cx="21" cy="21" r="16"/><circle className="progress" cx="21" cy="21" r="16"/></svg><span>92</span></div><div><b>Business health</b><small>Excellent · Live</small></div></div><div className="context-section"><span>Connected sources</span>{[{icon:ShoppingBag,label:'Sales & orders',meta:'Updated now',tone:'purple'},{icon:Boxes,label:'Inventory',meta:'1,248 SKUs',tone:'orange'},{icon:Users,label:'CRM pipeline',meta:'24 active deals',tone:'blue'},{icon:IndianRupee,label:'Finance',meta:'Synced 2m ago',tone:'green'}].map(s=><div className="source-item" key={s.label}><i className={s.tone}><s.icon/></i><span><b>{s.label}</b><small>{s.meta}</small></span><Check/></div>)}</div><div className="context-section"><span>In this conversation</span><div className="context-chip"><Package/><span><b>Inventory</b><small>8 products referenced</small></span><X/></div><div className="context-chip"><CalendarDays/><span><b>Current week</b><small>21–27 August</small></span><X/></div></div><div className="ai-tip"><Zap/><p><b>Pro tip</b><br/>Ask DOS to create actions, not just answer questions.</p></div></Glass>
    </div>
  </AdminShell>
}
